#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

docker build -t k3s package-k3s

# mkdir -p bin
# [ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
# CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/k3s-sonobuoy
